### PR TITLE
added a page with settings; added popup notification about other extensions

### PR DESCRIPTION
**Pull request by AnnaChervatyuk**

### CODE REVIEW

**Comment by Piterden** [comment]
Hi, dist folder shouldn't be included in repository!

**Review by Piterden — CHANGES_REQUESTED** [review]
You should exclude `dist` folder from your PR adding it to the `.gitignore` file!

**Comment by lk-geimfari** [comment]
@AnnaChervatyuk Can you, please, resolve conflicts or recreate PR?

**Comment by lk-geimfari** [comment]
@AnnaChervatyuk As we discussed, I'm closing this one to avoid conflicts.

**Pull request closed without merging**
